### ISSUE TITLE
Migrate ibissource projects to WeAreFrank repository

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#1364]
- [x] https://wearefrank.org/
- [x] https://github.com/wearefrank/
- [x] https://issues.sonatype.org/browse/OSSRH-85925
- [x] Migrate WeAreFrank.org
- [x] Migrate FrankFramework.org
- [x] How to migrate projects?
- [x] Migrate frank-doc-plugin
- [x] Migrate frank-doc
- [x] Add `relocation` tag to pom files.

**Comment by philipsens** [comment]
Also transfered frank-manual
