### ISSUE TITLE
EOL AngularJS is coming up, should we upgrade to Angular

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#1980]
**Describe the issue**
See https://docs.angularjs.org/misc/version-support-status. AngularJS LTS support ends on December 31, 2021.
Upgrade to Angular (TypeScript/NodeJS).

**Reporter**
Core-Team

### ngUpgrade preparations
 - [x] #4967
 - [x] Convert main controller to component
 - [x] Convert template + controller views to components
 - [x] #5134
 - [x] #5080

 ### ngUpgrade
- [x] Setup Angular with ngUpgrade (Matt)
- [x] Convert components, services, directives, filters, etc. to typescript
- [x] Convert angularjs components to angular components
- [x] Convert angularjs directives to angular directives
- [x] Convert angularjs services to angular services
- [x] Convert angularjs filters to angular pipes

### Standalone Angular
Needs research
- [x] Cleanup remaining angularjs files, configs & dependencies
- [x] Remove ngUpgrade
- [x] Fix styling

**Comment by nielsm5** [comment]
#5051
