### ISSUE TITLE
Centralized logging

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3194]
### Goal

logging in a containerized environment cannot be stored on the nodes filesystem

### Description

Depended on the cloud provider log4j2 will have different appenders to store the logging in a centralized environment, this needs to be implemented and tested
### Tasks 
- [ ] implement log4j appenders for aws and azure
- [ ] CloudWatchAppender
- [ ] Application Insights from Azure
- [ ] S3 buckets,
- [ ] Azure blob storage
- [ ] align with Splunk requirements (single file logging)?

**Comment by philipsens** [comment]
Some scenarios required me to gather logs of crashed pods, so I researched how to keep logs of pods on Kubernetes. I found some solutions using specific tooling like Fluend and Splunk (more: https://landscape.cncf.io/card-mode?category=logging&grouping=category). 
For the time being, I wanted an easy solution like persistent storage for each pod. This could be done with a PVC template in a replica set. But this would mean that a pod would get an existing PVC after scaling down and then up. Because of this, using persistent storage is not viable. 
I'll research some tooling in the future to connect as log4j appender.

**Comment by philipsens** [comment]
As a start, it would be helpful to log everything to system out in a containerized environment.

**Comment by nielsm5** [comment]
See also #6142, though it might be better to directly use the K8s implementations instead. See https://logging.apache.org/log4j/2.x/log4j-kubernetes

**Comment by Laurens-makel** [comment]
Just a little contribution, stuff to think about:

Regarding logging to Splunk in a k8s environment, in our poc we've realised this by deploying a Splunk Universal Forwarder with a Persistent Volume Claim with `accessMode: 'ReadWriteMany'` mounted to `/var/log/<app-name>`.

The same Persistent Volume Claim is mounted on the application instance under `/usr/local/tomcat/logs/<host-name>`, this allows multiple pods under the same deployment/replicaset.

We mount an `inputs.conf` file to the Splunk Universal Forwarder with a monitor statement on `/var/log/<app-name>/*/*(log|xml)` and extract the host using `host_segment=4`. Additionally, we've placed a script on the forwarder to delete pod specific folders in the monitored log directory after X hours of no new log lines.

**Comment by nielsm5** [comment]
After fiddling with #6142 for a day, I unfortunately came to the conclusion it's not possible to reconfigure Log4j2 successfully after it's been created. The only way to add custom appenders is by setting the property `log4j.configurationFile` which defaults to `log4j2.properties,log4j4ibis.xml` (comma separated). When overriding this system property(!) you can append your own file (which may be elsewhere on the filesystem).
