### ISSUE TITLE
Create generic way to read/write Multipart messages

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#3288]
### Goal
Simplify the use of multipart messages, on both (http) listeners and (http) senders.

### Description
Right now we have multiple implementations (such as multipartXmlSessionKey) to 'build' a multipart message. We have zipIterators and attachmentIterators, we should also implement a multipart iterator to read parts, or build a multipart message.
This will/should automatically add Multipart support for the ApiListener.

### Tasks 
- [x] #3925
- [x] #4880
- [x] #7290
- [ ] HttpSender Multipart Request
- [ ] HttpSender Multipart Response
- [ ] WebServiceSender Multipart Request
- [ ] WebServiceSenderMultipart Response
- [x] ApiListener Multipart Request
- [x] ApiListener Multipart Response (#3018)
- [ ] ForEachMultipartPipe

**Comment by jacodg** [comment]
Make a start in 7.9 and finish in 8.0

**Comment by evandongen** [comment]
Multiparts should be set in its own map in the PipeLineSession. See #11382

**Comment by evandongen** [comment]
@nielsm5 can you check what the status is for the open points?

**Comment by nielsm5** [comment]
The intent of this issue was to ensure that the part produced by:
https://github.com/frankframework/frankframework/blob/e1631b3d1ba306a27c115120085f5da44883db8c/core/src/main/java/org/frankframework/http/mime/HttpEntityFactory.java#L326-L335

Is equal to:
https://github.com/frankframework/frankframework/blob/e1631b3d1ba306a27c115120085f5da44883db8c/core/src/main/java/org/frankframework/http/mime/MultipartUtils.java#L242-L250

**Comment by nielsm5** [comment]
The one outlier that doesn't use either methods is; https://github.com/frankframework/frankframework/blob/e1631b3d1ba306a27c115120085f5da44883db8c/core/src/main/java/org/frankframework/http/WebServiceListener.java#L190-L201
