### ISSUE TITLE
LCM - migration junit 4 to junit 5

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#4282]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Migrate the iaf-core junit 4 tests to junit 5 where possible

- [x] #4292 
- [x] #5626
- [x] Convert SenderTestBase
- [x] Convert PipeTestBase
- [ ] Convert Database enabled tests
- [x] testGetRollingFileTheSamefile() in FileUtilsTest
- [x] Convert FileSystemTests
- [ ] Convert HttpSenderAuthenticationTest
- [ ] Convert DbmsSupportTest -> Yannick has a lot of changes already locally
- [ ] Convert MessageStoreListenerTest -> Yannick has a lot of changes already locally

**Reporter**
Vinh

**Comment by nielsm5** [comment]
FileUtilsTest#testGetRollingFileTheSamefile has a disabled method

**Comment by Yale96** [comment]
I added that one to the list indeed

**Comment by nielsm5** [comment]
Database related tests have been migrated, I've created a new issue regarding the last 8 classes #6251.
