### ISSUE TITLE
JDK11 - 8.0 Milestone

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#5637]
### Goal
The goal is to migrate fully to Java 11 and restructure our code by dividing it into new modules.

### Description
We're dropping WebSphere support, officially changing our product name and are moving to a new marjor version (8.x).

### Administrative Tasks 
- [x] #5484
- [x] #5802
- [x] Rename all artifacts from `ibis-adapterframework` to `frankframework`
- [x] Change package structure from `nl.nn.adapterframework.` to `org.frankframework.` #1711
- [x] Migration from ibissource to frankframework

### Code cleanup
- [x] Remove `@Deprecated` methods - part 1
    * SambaSenderOld. ✅ 
    * isStreamResultToServlet  ✅ 
    * isStreamResultToServlet: JdbcQuerySenderBase ⛔ 
    * FileUtils contains quite a few unused methods  ✅ 
    * GenericMessageSendingPipe  ✅ 
    * XsltSender/Pipe+ForEachChildElementPipe+Parameter #setXslt2(boolean) ✅ 
- [x] Remove `@Deprecated` methods - part 2
    * GenericReceiver ✅ 
    * MdcPipe ✅ 
    * IsXmlIfPipe ✅ 
    * LdapQueryPipeBase + HttpSenderBase #setUserName (and #setProxyUserName)  ✅ 
    * JmsFacase#setAckMode  ✅ 
    * CompareStringPipe/CompareIntegerPipe SessionKey1/SessionKey2  ✅ 
    * HttpSender setMultipart, setMtomEnabled, setInputMessageParam  ✅ 
    * HttpSender setStoreResultAsXYZInSessionKey ✅ 
- [x] #5741
- [ ] #5742
- [x] #5740
- [x] #5525
- [x] #5654
- [x] #5725
- [x] #5722
- [x] #5760
- [x] #5759
- [x] #5758
- [x] #5855
- [x] Move the following packages to a new module (#5735)
    * extensions.svn
    * extensions.afm
    * extensions.bis
    * extensions.ifsa
    * extensions.xfb
    * extensions.api
    * extensions.esb
    * extensions.rekenbox
    * xcom
- [ ] Move jms package to it's own module
    * including extensions.mqtt (#5733)
- [x] #5767
- [x] Move `extensions.javascript` to `javascript` (#5730)
    * Remove `Rhino` and `Nashorn` (inc Promise.js) (#5489)
    * Add `org.graalvm.js` (#5496)
- [x] #5762
- [x] #5989
- [x] Remove IBM module (#5724)
    * Move extensions.ibm code to JMS module
- [x] #5664
- [ ] #6362
- [ ] #6363

Potentially also remove:
- Samba1FileSystem
- jta.btm

### Dependency cleanup
- [x] #5558
- [ ] servicemix
- [ ] implement new Java mail API
- [ ] jakarta -> upgrades
    * Spring
    * CXF
- [x] saaj, jaas, xml-apis
- [ ] Everything starting with com.sun

**Comment by nielsm5** [comment]
Closing this for now. Issues have been created for the last remaining tasks.
