### ISSUE TITLE
WebSocket communication between Console frontend and backend (modern alternative for poller)

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6562]
### Goal
Add additional way of polling via WebSockets where the events/changes from the backend are send as "events" to the frontend

### Description
**Is your feature request related to a problem? Please describe.**
Currently, our console frontend relies on a polling mechanism to fetch updates from the backend. This approach can lead to unnecessary network traffic and delays in data updates, as the frontend continuously requests information at a set interval, regardless of whether there are changes.

**Describe the solution you'd like**
I propose the implementation of WebSocket communication between the console frontend and backend. WebSockets provide a full-duplex communication channel over a single, long-lived connection, allowing the server to push updates to the frontend instantly when data changes. This would be a more modern and efficient alternative to the current poller system.

**Describe alternatives you've considered**
An alternative could be to use Server-Sent Events (SSE), which also allows the server to push updates to the client. However, SSE is unidirectional, and for our use case, a bidirectional communication channel like WebSockets would be more beneficial.

**Additional context**
The adoption of WebSockets would not only reduce network load but also provide a more responsive user experience. It would allow for real-time updates without the need to refresh the page or wait for the next polling interval. Additionally, this change would align our architecture with modern web development practices, potentially making it easier to maintain and scale in the future.

### Tasks 
- [x] Research if websockets can be made with CXF, if not how to implement with Spring web. Also how to potentially migrate everything from CXF to Spring web
- [x] Console backend support for WebSocket endpoints
- [x] Console frontend can connect to WebSocket endpoints
- [x] Console send & retrieve adapter info & (state) changes through WebSocket
- [x] Setup SockJS as fallback
- [ ] Figure out if scheduled methods can be tested & write tests

**Comment by Laurens-makel** [comment]
Will this be additional to the existing REST API or will this be a replacement?

Please consider that the current REST API is used by other solutions, we have a monitoring tool which heavily relies on the REST API to check for example if there are any records in any error storage.

**Comment by Matthbo** [comment]
It will be an addition.
The websockets will be used only as a better way to pick up any configuration/adapter updates as they happen which hopefully will be a more efficient way for the Console frontend to be up-to-date with what happens in the framework instead of polling every x seconds and getting all the adapter information each time.
Nothing will or should change in the API except for new web sockets endpoint(s).

I'm also aware that using websockets is not always possible (or allowed in certain enviroments) so the polling will also stay for those cases.

**Comment by Matthbo** [comment]
CXF doesn't seem to have proper support for the WebSocket protocol.
The only documentation available mentions `CXF 3.0.0-SNAPSHOT` and while it exists on the 3.5.x API, it doesn't seem to have any proper documentation/Javadoc on the 3.6.x or 4.0.x API.
In terms of samples / examples it looks like the endpoints to handle the WebSocket protocol are made to look the exact same as regular rest endpoints using JAX-RS, its unclear if there is a way to keep pushing data to the client (events).
[CXF WebSocket page](https://cxf.apache.org/docs/websocket.html)

**Comment by Matthbo** [comment]
Spring Web seems to have much better documentation and support for handling WebSocket's.
It has a [WebSocket API](https://docs.spring.io/spring-framework/reference/web/websocket/server.html), a fallback with [SockJS](https://docs.spring.io/spring-framework/reference/web/websocket/fallback.html) (using XHR to emulate WebSocket behaviour) & a protocol called [STOMP](https://docs.spring.io/spring-framework/reference/web/websocket/stomp.html) which can be used to define the types of messages going over the WebSocket.

Using this however would mean that we need to migrate the Console Backend from JAX-RS over to Spring Web.
Spring Web MVC is recommended for this because it has endpoint annotations & response handling similar to JAX-RS or even better because it also supports writers directly as the return type of an endpoint

**Comment by Matthbo** [comment]
#6676 has been made and is required in order to continue with this feature
