### ISSUE TITLE
Migrate Console Backend from JAX-RS to Spring Web MVC

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6676]
### Goal
Migrate from CXF using JAX-RS for API endpoints to Spring Web MVC

### Description
The Console Backend currently relies on the CXF implementation of JAX-RS for handling RESTful services like the API endpoints. However, we've decided to migrate to Spring Web MVC as Spring is already being used and CXF with JAX-RS lacks  proper support for things like WebSocket's or other modern web services.

### Tasks 
- [x] Add Spring Web MVC as a dependency
- [x] Run JAX-RS equivalents endpoints using Spring next to existing endpoints
- [x] Remove JAX-RS endpoints
- [x] Remove CXF dependencies
- [x] Change implementations to Spring Web only

**Comment by evandongen** [comment]
See https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet/multipart.html - in spring 6, the default behavior of multipart has been changed, make sure to use setMultipartConfig and add a bean named 'multipartResolver'.
