### ISSUE TITLE
Native JSON support 

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#6883]
### Goal
More native support for JSON and YAML  
"Frank-developers mostly convert JSON to XML and than map it using XSLT, any Josn2json mapping can be done using JavaScript pipe" 

### Description
We need equivalents for 
XSLTPipe ==> JSTL (JSON mapping)  ==> JSLTPipe
XPATH ==> JSONpath ==> PARAM /  JsonIfPipe / other XPATH pipes
XSD validation ==> Validation against API Spec or JSON schema

### Tasks 
- [ ] add JSLT pipe
- [ ] add JSON path to param
- [ ] add JSON IfPipe
related older issues
- [ ] #1634
- [ ] #6491
- [ ] #5057

Slightly related:
XML Object Notation  ==> using a XML format that can convert from and to JSON without
- [] #5534

javascript pipe is now used for JSON mapping
- [] #6239

**Comment by nielsm5** [comment]
Keertje met @mlenterman er over hebben?

**Comment by MLenterman** [comment]
> Keertje met @MLenterman er over hebben?

Ja, goed idee! Donderdag?

**Comment by MLenterman** [comment]
jq(json) and yq(yaml) are direct alternatives to XQuery for XML.

SDTL is a generic transformation language for structured data: [SDTL](https://ddialliance.org/products/sdtl/1.0). Would tackle all the advanced use-cases that XSLT can at the minimum, but also extremely complex. Unclear what the state/usage of that language is atm. Not a big fan it, but an option to consider.

For simpler cross-format transformations perhaps a templating engine would be more fitting and easier to use. [Handlebars](https://handlebarsjs.com/) or [Nunjucks](https://mozilla.github.io/nunjucks/) seem good options for this.

JSLT seems to be the most useable alternative to XSLT for XML. I personally dislike using XSLT/JSLT complexity languages for most transformations, because the feature richness simply gets in the way when you only require a simple and straight forward transformation. But having a transformation language available for those advanced use-cases is still needed. JSLT checks out for that.

**Comment by nielsm5** [comment]
[JSonnet](https://jsonnet.org/) see #7303 as Json data mapper. See [https://datasonnet.github.io/datasonnet-mapper/datasonnet/latest/cookbook.html](datasonnet cookbook) for examples.

**Comment by nielsm5** [comment]
Some sub-issues, such as json capable ErrorMessageFormatters, have their own Epic, see https://github.com/frankframework/frankframework/issues/8748.
