### ISSUE TITLE
Improve SonarCloud results

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6980]
### Goal
SonarCloud is not happy, goal is to make SonarCloud happy.

### Description
We have the following open issues:
[39 Security Issues](https://sonarcloud.io/project/issues?impactSoftwareQualities=SECURITY&resolved=false&id=ibissource_iaf)
[209 Reliability Issues](https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&resolved=false&id=ibissource_iaf)
[4.1k Maintainability Issues](https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=ibissource_iaf)

As well as a coverage of [55.8%](https://sonarcloud.io/component_measures?id=ibissource_iaf&metric=new_coverage&view=list) on `New Code` and `50%` on `Overall Code`. 

### Tasks 
Improve JUnit coverage for:
- [x] Common -> XmlEncodingUtils, StreamUtils, ClassUtils
- [x] [Console Backend](https://github.com/frankframework/frankframework/pull/7180)
- [ ] Batch
- [ ] Messaging -> MQTT
- [ ] NN-Specials
- [ ] FileSystem -> IMAP filesystem
- [ ] Core -> LDAP package
- [x] Core -> XmlQuerySender class

See if there are any quick wins to reduce the amount of Maintainability Issues.

**Comment by nielsm5** [comment]
See #7277
