### ISSUE TITLE
Replace remaining static asString(message) usages

### ISSUE THREAD

**Issue by evandongen** [frankframework/frankframework#7078]
### Goal

To remove the last usages of the static 'asString' method. This items are all more complex and probably need some more research and or changes to how they work at the moment.

### Description

After working on ticket #6298 , we encountered a few not so easy to replace usages of the static asString method. For now, `Message.asString` has been moved to `MessageUtils` to at least remove the static methods from Message.

### Tasks

- [ ] Use a ParameterValue in `FixedForwardPipe` instead of the current implementation for `ifParameter`. 
This should enable us to use a `ParameterValue#asStringValue` instead of `MessageUtils.asString`
- [ ] Use a ParameterValueList in `JwtPipe` to be able to skip using `MessageUtils.asString` in `#getSigner()` method.
- [ ] Refactor the `RemoveFromSession` pipe. 
- [ ] Analyze and refactor `.JdbcUtil#getBlobAsString` to remove usage of MessageUtils.asString
- [ ] Analyze and refactor `MessageBrowsingUtil#getMessageText` to remove usage of MessageUtils.asString
- [ ] Remove the usage of MessageUtils.asString in `XmlUtils#setTransformerParameters`

**Comment by nielsm5** [comment]
Hopefully after #10141 we hopefully have target 'sanitization' method(s). So after that ticket we can hopefully decide what to do with this ticket.
